version: "3"

services:
  mcpv2:
    image: v2fly/v2fly-core:v4.45.2
    container_name: mcpv2
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "2"
    volumes:
      - ./:/usr/local/share/v2ray
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep -f get_server_config && pgrep -f v2scar_alpine || echo 1"]
      interval: 30s
      timeout: 3s
      retries: 1
      start_period: 15s
    command: sh -c "chmod +x /usr/local/share/v2ray/v2scar_alpine && /usr/local/share/v2ray/v2scar_alpine -id=${nodeId} -gp=127.0.0.1:8079 & /usr/local/share/v2ray/xray run -c /usr/local/share/v2ray/server_config.json -format json"
